### ISSUE TITLE
Establish cost of hosting in Azure for small businesses

### ISSUE THREAD

**Issue by RichardMellerGibbs** [asudbury/spectrum#2]
What is the minimum cost a business can expect to pay for low volume traffic?

**Comment by asudbury** [comment]
Microsoft provider this calculator to work out costings

https://azure.microsoft.com/en-gb/pricing/calculator/

i always struggle to use it though - a lot depends on traffic etc.

i think the cheapest you can do is about £10 a month - but you dont get SSL with that option.

the next tier up is looking at £40 per month - but i think that allows multiple websites and you only pay for what you use.

Ill try and have another look at it.

**Comment by asudbury** [comment]
too expensive!
