### ISSUE TITLE
Weekly StandUp Meeting

### ISSUE THREAD

**Issue by asudbury** [asudbury/spectrum#4]
We need to agree a regular time where we commit to an hour to discuss what we are going to work on etc.

This should part of a planning meeting for a sprint where we agree what we will work on for the next 2 weeks.

**Comment by RichardMellerGibbs** [comment]
This might work best in front of my laptop so we can look at the code/screens during the meetings. I guess it could be done via hangout but perhaps the lunchtime meet might be better.
Do you want to try lunchtimes?

**Comment by asudbury** [comment]
Monday lunch time - limited to 20min-30mins - if we havent finished then
Monday Evening time to be agreed.

**Comment by asudbury** [comment]
communications happens pretty much on a daily basis - suggest weekly call is 6pm Monday Evening.
